### ISSUE TITLE
[Next.js] 개인과제 피드백 - 김병연 튜터

### ISSUE THREAD

**Issue by ByungyeonKim** [G-NooN/todo-list-with-next#1]
안녕하세요, 진훈님.

벌써 Next.js라니..금방 또 4월 되겠네요. 🧐 시간 참 빠르죠? 진훈님은 Next.js 사용하신 소감이 어떠신가요?
나중에 시간 되시면 자리에 들러주셔요. 경험담 같이 나눠봐요~

# LICENSE

`LICENSE` 파일도 추가 하셨군요?! 저는 한번도 추가해본 적이 없어서 그런지, 추가하신 이유가 궁금해요! 어쩌다 추가하게 되셨는지 알려주시면 감사하겠습니다. :)

# NPM 스크립트

https://github.com/G-NooN/todo-list-with-next/blob/dc777d8df2ea23cc86006a3d9726575fb90a994e/package.json#L10

이렇게 자주 사용하는 스크립트를 등록해 두면, 편리할 뿐만 아니라 해당 프로젝트에 참여하는 모든 개발자들도 쉽게 실행할 수 있죠. 좋네요. 👍

# 커스텀 훅 네이밍

https://github.com/G-NooN/todo-list-with-next/blob/dc777d8df2ea23cc86006a3d9726575fb90a994e/src/hooks/useTodoQuery.ts#L6

https://github.com/G-NooN/todo-list-with-next/blob/dc777d8df2ea23cc86006a3d9726575fb90a994e/src/hooks/useTodoQuery.ts#L24

https://github.com/G-NooN/todo-list-with-next/blob/dc777d8df2ea23cc86006a3d9726575fb90a994e/src/hooks/useTodoQuery.ts#L50

https://github.com/G-NooN/todo-list-with-next/blob/dc777d8df2ea23cc86006a3d9726575fb90a994e/src/hooks/useTodoQuery.ts#L70

일반적으로 앱에서 필요에 의한 우리만의 훅을 정의할 때 커스텀 훅이라 하고, 네이밍을 할 때 접두사로 `use`를 붙이죠. 탠스택 쿼리도 마찬가지에요. 접두사로 `use`를 붙여서 네이밍하는 게 좋다고 생각해요.

- https://tkdodo.eu/blog/practical-react-query#treat-the-query-key-like-a-dependency-array
- https://github.com/TanStack/query/blob/main/examples/react/nextjs/src/hooks/usePosts/index.js

위의 예시처럼 http 로직은 함수로 따로 빼서 리팩토링 해보는 것도 좋을 것 같아요!

---

이번 과제도 정말 고생하셨습니다! 👏

**Comment by G-NooN** [comment]
감사합니다!!
